name: push auto pr create and merge

on:
  push:
    branches-ignore:
      - main
  #workflow_dispatch:

permissions: write-all

defaults:
  run:
    shell: bash

jobs:
  main:
    runs-on: [self-hosted, linux]
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: pr_create
        id: pr_create
        run: |
          pr_url=$( \
            gh pr create \
              --base main \
              --title "push auto pr create" \
              --body "push auto pr create" \
              --assignee ${{ github.actor }} \
          )
          echo "pr_url is ${pr_url}"
          echo "pr_url=${pr_url}" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_GITHUB_RUNNER }}

      #- name: pr_approve
      #  id: pr_approve
      #  uses: hmarr/auto-approve-action@v4

      - name: pr_merge
        id: pr_merge
        run: |
          gh pr merge \
            ${{ steps.pr_create.outputs.pr_url }} \
            --merge \
            --auto \
            --body "push auto pr merge"
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_GITHUB_RUNNER }}
