name: auto approve

on:
  - pull_request_target

permissions:
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  main:
    runs-on: [self-hosted, linux]
    steps:
      - name: approve
        uses: hmarr/auto-approve-action@v4
