name: push auto pr merge

on:
  pull_request_target:
    types:
      - opened

permissions: write-all

defaults:
  run:
    shell: bash

jobs:
  main:
    runs-on: [self-hosted, linux]
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: pr_approve
        id: pr_approve
        uses: hmarr/auto-approve-action@v4

      - name: pr_merge
        id: pr_merge
        run: |
          gh pr merge \
            ${{github.event.pull_request.html_url}} \
            --merge \
            --auto \
            --body "push auto pr merge"
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_GITHUB_RUNNER }}
