name: check_runner

on:
  workflow_dispatch:

permissions: write-all

defaults:
  run:
    shell: bash

jobs:
  step:
    runs-on: [self-hosted, linux]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: runner status
        run: |
          echo ls -al: $(ls -al)
          echo ---------------------------------------
          echo pwd: $(pwd)
          echo ---------------------------------------
          echo lsb_release: $(lsb_release -a)
          echo ---------------------------------------
          echo uname -n: $(uname -n)
          echo ---------------------------------------
          echo docker version: $(docker version)
          echo ---------------------------------------
          echo docker buildx version: $(docker buildx version)
          echo ---------------------------------------
