name: image build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

defaults:
  run:
    shell: bash

jobs:
  main:
    runs-on: [self-hosted, linux]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: check_diff
        run: |
          files=($(git diff HEAD^ --name-only|tr '\n' ' ' ))
          for file in ${files[@]}; do
            echo ${file}
          done
