name: image build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

defaults:
  run:
    shell: bash

jobs:
  main:
    runs-on: [self-hosted, linux]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: check_diff
        run: |
          files=($(git diff HEAD HEAD^ --name-only|tr '\n' ' ' ))
          for file in ${files[@]}; do
            if [ -n "$(echo ${file} | sed -nEe '/Dockerfile/p')" ] && [ -e ${file} ]; then
              imagename=$(echo ${file} | cut -d '/' -f 1)
              nowdata=$(date '+%Y%m%d-%H%M')
              echo "imagename is ${imagename}"
              echo "nowdata   is ${nowdata}"
              #docker build . \
              #  -f ./Dockerfile_${imagename} \
              #  -t img.home.xdr-s.net/${imagename}:${nowdata}
              #docker tag \
              #  img.home.xdr-s.net/${imagename}:${nowdata} \
              #  img.home.xdr-s.net/${imagename}:latest
              #docker push img.home.xdr-s.net/${imagename}:${nowdata}
              #docker push img.home.xdr-s.net/${imagename}:latest
            fi
          done
