name: image build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

defaults:
  run:
    shell: bash

jobs:
  setup:
    runs-on: [self-hosted, linux]
    outputs:
      diff_parse: ${{ steps.diff_parse.outputs.value1 }}
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: docker_login
        id: docker_login
        uses: docker/login-action@v3
        with:
          registry: harbor.home.xdr-s.net
          username: ${{ secrets.HARBOR_ID }}
          password: ${{ secrets.HARBOR_PW }}

      - name: diff_parse
        id: diff_parse
        run: |
          files=($(git diff HEAD HEAD^ --name-only|tr '\n' ' ' ))
          first=true
          out="[" && for file in "${files[@]}"; do
            if [ -n "$(echo "${file}" | sed -nEe '/Dockerfile/p')" ] && [ -e "${file}" ] && [ ${#file} -gt 12 ]; then
              repo=$(echo "${file}" | cut -d '/' -f 1)
              image=$(echo "${file}" | cut -d '/' -f 2)
              if [ "${first}" != "true" ]; then out+=","; fi
              out+="{\"repo\":\"${repo}\",\"image\":\"${image}\"}"
              first=false
            fi
          done && out+="]"
          echo ${out} | jq .
          echo "value1=${out}" >> $GITHUB_OUTPUT

  build:
    runs-on: [self-hosted, linux]
    needs: setup
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        diff_parse: ${{fromJson(needs.setup.outputs.diff_parse)}}
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: docker_login
        id: docker_login
        uses: docker/login-action@v3
        with:
          registry: harbor.home.xdr-s.net
          username: ${{ secrets.HARBOR_ID }}
          password: ${{ secrets.HARBOR_PW }}

      - name: docker_build
        id: docker_build
        run: |
          nowdata=$(date '+%Y%m%d-%H%M')
          regname=harbor.home.xdr-s.net
          reponame=$(echo ${{ matrix.diff_parse.repo }})
          imagename=$(echo ${{ matrix.diff_parse.image }})
          echo "build filename is ${reponame}/${imagename}/Dockerfile"
          echo "build imagename is ${regname}/${reponame}:***"
          pushd ${reponame}/${imagename}
          #docker builder prune -af
          #docker build -t ${regname}/${reponame}/${imagename}:${nowdata} .
          #docker tag  ${regname}/${reponame}/${imagename}:${nowdata} \
          #            ${regname}/${reponame}/${imagename}:latest
          #docker push ${regname}/${reponame}/${imagename}:${nowdata}
          #docker push ${regname}/${reponame}/${imagename}:latest
          #docker builder prune -af
          popd
