name: image build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

defaults:
  run:
    shell: bash

env:
  regname: harbor.home.xdr-s.net

jobs:
  setup:
    runs-on: [self-hosted, linux]
    outputs:
      diff_parse: ${{ steps.diff_parse.outputs.value1 }}
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: diff_parse
        id: diff_parse
        run: |
          files=($(git diff HEAD HEAD^ --name-only|tr '\n' ' ' ))
          first=true
          out="[" && for file in "${files[@]}"; do
            if [ -n "$(echo "${file}" | sed -nEe '/Dockerfile/p')" ] && [ -e "${file}" ] && [ ${#file} -gt 12 ]; then
              repo=$(echo "${file}" | cut -d '/' -f 1)
              image=$(echo "${file}" | cut -d '/' -f 2)
              if [ "${first}" != "true" ]; then out+=","; fi
              out+="{\"repo\":\"${repo}\",\"image\":\"${image}\"}"
              first=false
            fi
          done && out+="]"
          echo ${out} | jq .
          echo "value1=${out}" >> $GITHUB_OUTPUT

  build:
    runs-on: [self-hosted, linux]
    needs: setup
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        diff_parse: ${{fromJson(needs.setup.outputs.diff_parse)}}
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: docker_setup_buildx
        id: docker_setup_buildx
        uses: docker/setup-buildx-action@v3

      - name: docker_login
        id: docker_login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.regname }}
          username: ${{ secrets.HARBOR_ID }}
          password: ${{ secrets.HARBOR_PW }}

      - name: nowdate
        id: nowdate
        run: echo "value1=$(date '+%Y%m%d-%H%M')" >> $GITHUB_OUTPUT

      - name: docker_build_push
        uses: docker/build-push-action@v6
        with:
          push: true
          no-cache: true
          platforms: linux/amd64
          context: ${{ matrix.diff_parse.repo }}/${{ matrix.diff_parse.image }}
          tags: |
            ${{ env.regname }}/${{ matrix.diff_parse.repo }}/${{ matrix.diff_parse.image }}:${{ steps.nowdate.outputs.value1 }}
            ${{ env.regname }}/${{ matrix.diff_parse.repo }}/${{ matrix.diff_parse.image }}:latest
