name: push pr create

on:
  push:
    branches:
      - feature/*

permissions: write-all

defaults:
  run:
    shell: bash

jobs:
  main:
    runs-on: [self-hosted, linux]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Create pull request
        run: gh pr create --base main --title "push pr create" --body "push pr create" --assignee ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{secrets.PRIVATE_GITHUB_ACTIONS}}
